config:
  node_agent: 'docker_compose'
  deploy_template: '.sqa/docker-compose.yml'
  project_repos:
    worsica_processing:
      repo: 'https://github.com/WORSICA/worsica-processing'
      branch: development
      credentials_id: worsica-bot-github
    worsica_intermediate:
      repo: 'https://github.com/WORSICA/worsica-intermediate'
      branch: development
      credentials_id: worsica-bot-github
    worsica_frontend:
      repo: 'https://github.com/WORSICA/worsica-frontend'
      branch: development
      credentials_id: worsica-bot-github
    WORSICA_github_io:
      repo: 'https://github.com/WORSICA/WORSICA.github.io'
      branch: development
      credentials_id: worsica-bot-github
#   dataverse-docker:
#     repo: 'https://github.com/IQSS/dataverse-docker'
#     branch:  master
  credentials:
      - id: worsica-bot-github
        username_var: GIT_USER
        password_var: GIT_TOKEN
      - id: worsica-bot-dockerhub-token
        username_var: JPL_DOCKERUSER
        password_var: JPL_DOCKERPASS
      - id: worsica-postgis-password
        variable: POSTGRES_PASSWORD
      - id: worsica-rabbitmq-corsica
        username_var: RABBITMQ_USER
        password_var: RABBITMQ_PASSWORD
      - id: worsica-sentinel-secret
        username_var: WORSICA_SSECRET_USER
        password_var: WORSICA_SSECRET_PASSWORD
      - id: worsica-nextcloud-credentials
        username_var: WORSICA_NEXTCLOUD_USER
        password_var: WORSICA_NEXTCLOUD_PASSWORD
      - id: worsica-dataverse-credentials
        username_var: WORSICA_DATAVERSE_USER
        password_var: WORSICA_DATAVERSE_PASSWORD

sqa_criteria:
  qc_functional: #functional/unitary + coverage
    repos:
      worsica_processing:
        container: processing
        tox:
          testenv:
            - worsica-processing-unittest
          tox_file: '/usr/local/worsica_web_products/tox.ini'
      worsica-intermediate:
        container: intermediate
        tox:
          testenv:
            - worsica-intermediate-functional
          tox_file: '/usr/local/worsica_web_intermediate/tox.ini'
      worsica_frontend:
        container: frontend
        tox:
          testenv:
            - worsica-portal-functional
          tox_file: '/usr/local/worsica_web/tox.ini'
          
#  qc_coverage:
#    repos:
#      worsica_processing:
#        container: processing
#        tox:
#          testenv:
#            - worsica-processing-coverage
#          tox_file: '/usr/local/worsica_web_products/tox.ini'
#      worsica_intermediate:
#        container: intermediate
#        tox:
#          testenv:
#            - worsica-intermediate-coverage
#          tox_file: '/usr/local/worsica_web_intermediate/tox.ini'
#      worsica_frontend:
#        container: frontend
#        tox:
#          testenv:
#            - worsica-portal-coverage
#          tox_file: '/usr/local/worsica_web/tox.ini'

#  qc_style:
#    repos:
#      worsica_processing:
#        container: processing
#        tox:
#          testenv:
#            - worsica-processing-stylecheck
#          tox_file: '/usr/local/worsica_web_products/tox.ini'
#      worsica_intermediate:
#        container: intermediate
#        tox:
#          testenv:
#            - worsica-intermediate-stylecheck
#          tox_file: '/usr/local/worsica_web_intermediate/tox.ini'
#      worsica_frontend:
#        container: frontend
#        tox:
#          testenv:
#            - worsica-portal-stylecheck
#          tox_file: '/usr/local/worsica_web/tox.ini'
          
#  qc_security:
#    repos:
#      worsica-processing:
#        container: processing
#        tox:
#          testenv:
#            - worsica-processing-security
#          tox_file: '/usr/local/worsica_web_products/tox.ini'
#      worsica-intermediate:
#        container: intermediate
#        tox:
#          testenv:
#            - worsica-intermediate-security
#          tox_file: '/usr/local/worsica_web_intermediate/tox.ini'
#      worsica_frontend:
#        container: frontend
#        tox:
#          testenv:
#            - worsica-portal-security
#          tox_file: '/usr/local/worsica_web/tox.ini'
  qc_doc:
    repos:
      WORSICA_github_io:
        container: sphinx
        commands:
          - make -C "/usr/local/WORSICA.github.io" multiversion

environment:
  JPL_DOCKERPUSH: "essentials processing intermediate frontend sphinx"
  #JPL_IGNOREFAILURES: "defined"
  JPL_DOCKERFORCEBUILD: "enabled"
  JPL_WORKSPACEDEBUG: "true"
  JPL_WORKSPACEDEBUGTIMEOUT: 45

timeout: 1200
